name: Deploy

on: 
  push:
    branches: 
      - master

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to server
      working-directory: ./backend
      run: |
        git remote add umbler https://geonosis.deploy.umbler.com/kqx7n25e/patricksuyti-com-br.git
        git push umbler master
